version: '2'
services:
  server:
    build: .
    environment:
      DATABASE_URL: postgres://postgres:example@db:5432/forum_development
    ports:
      - "3000:3000"
    links:
      - db

  db:
    image: postgres:9
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
