connection: &connection
  url: <%= ENV['DATABASE_URL'] %>  
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: example

development:
  <<: *connection
  database: forum_development

test:
  <<: *connection
  database: forum_test

production:
  <<: *connection
  database: forum_production
