connection: &connection
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: dguedes
  password: progressive

development:
  <<: *connection
  database: forum_development

test:
  <<: *connection
  database: forum_test

production:
  <<: *connection
  database: forum_production
